name: Python application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10' 
      - name: Install dependencies
        run: python.exe -m pip install --upgrade pip PyInstaller PySide6 && python.exe -m pip install -r src\requirements.txt
      - name: Build package
        run: python.exe -m PyInstaller --icon .\src\fileicon.ico .\src\notepy.pyw --onefile
      - uses: actions/upload-artifact@v4
        with:
            name: NotePy
            path: .
      
